### ISSUE TITLE
Add alloys?

### ISSUE THREAD

**Issue by kyleplo** [SyKoNetwork/MCBE-Unified-Ore#19]
I know a lot of addons like using alloys as well as ores, so I think it would be neat if this project contained alloys made with both the ores in the project as well as vanilla ores.

Alloy suggestions:
- Steel (iron + coal)
- Brass (copper + zinc)
- Bronze (copper + tin)
- Rose Gold (copper + gold)
- Constantan (copper + nickel)
- Invar (iron + nickel)

This is a decently long list, so I don’t think all of these need to be added.
Some sort of way of crafting alloys should also be added.

**Comment by SykoUSS** [comment]
This is something that has been discussed as well. We aren't sure if we want to directly include alloys into the "Unified Ore" creator pack, or perhaps a new pack called "Unified Alloys". Even though we haven't made a decision yet about how to incorporate them, it is something we want to do!
