### ISSUE TITLE
What would be a good first contribution?

### ISSUE THREAD

**Issue by outercloudstudio** [SyKoNetwork/MCBE-Unified-Ore#3]

**Comment by SykoUSS** [comment]
Hmm, what do you have in mind? There is no true end goal, aside from having everything we can think of.

**Comment by outercloudstudio** [comment]
Silver is a common ore in mods and addons. Would I need to create a texture and the correct rules along with the block?

**Comment by SykoUSS** [comment]
Feel free to do as much as you would like, most of what is needed is the unique textures for the rp side. And maybe an idea of where it would generate for the bp. If you want, you can make a copy of the tin block/rules and use it as a template.

**Comment by outercloudstudio** [comment]
Should I make a deepslate and normal variant? If so, where would I find the base textures?

**Comment by SykoUSS** [comment]
Yes, please
